sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t mehtaanirudh/docker-react .

script:
  - docker run -e CI=true mehtaanirudh/docker-react npm run test  

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"  
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-eu-west-2-205474902674"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"